##### ### The University of Melbourne, School of Computing and Information Systems
# COMP30027 Machine Learning, 2026 Semester 1

## Assignment 1: Income Classification with Naïve Bayes

**Student ID(s):**     1524206

This iPython notebook is a template which you will use for your Assignment 1 submission.

**NOTE: YOU SHOULD ADD YOUR RESULTS, GRAPHS, AND FIGURES FROM YOUR OBSERVATIONS IN THIS FILE TO YOUR REPORT (the PDF file).** Results, figures, etc. which appear in this file but are NOT included in your report will not be marked.

**Adding proper comments to your code is MANDATORY. **

## 1. Supervised model training

### Import libraries

In [43]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, CategoricalNB
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OrdinalEncoder
import matplotlib.pyplot as plt

### Reading and pre-processing data

In [44]:

# Reading and pre-processing data
data = pd.read_csv('Assignment1_data/adult_supervised_train.csv', sep=',')
data = data.dropna(how='all')

continuous_features = data[['age','education-num','capital-gain','capital-loss','hours-per-week']]
categorical_features = data[['workclass','education','marital-status','occupation','relationship','race','sex','native-country']]
display(continuous_features)
display(categorical_features)
y = data['income']
display(y)

       age  education-num  capital-gain  capital-loss  hours-per-week
0       63              4          3471             0              45
1       44             14          7688             0              50
2       18              8             0             0              30
3       39             12             0             0              42
4       28              6             0             0              40
...    ...            ...           ...           ...             ...
16275   19              7             0             0              56
16276   27             13             0          1887              60
16277   45              9             0             0              40
16278   25              6             0             0              45
16279   29              9             0             0              40

[16280 rows x 5 columns]

,workclass,education,marital-status,occupation,relationship,race,sex,native-country
0,Private,7th-8th,Married-civ-spouse,Craft-repair,Husband,White,Male,United-States
1,State-gov,Masters,Married-civ-spouse,Prof-specialty,Husband,White,Male,United-States
2,Private,12th,Never-married,Other-service,Own-child,White,Male,Italy
3,Private,Assoc-acdm,Married-civ-spouse,Tech-support,Husband,White,Male,United-States
4,Private,10th,Never-married,Handlers-cleaners,Other-relative,White,Male,Mexico
...,...,...,...,...,...,...,...,...
16275,Private,11th,Never-married,Craft-repair,Not-in-family,White,Male,United-States
16276,Private,Bachelors,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,United-States
16277,State-gov,HS-grad,Separated,Sales,Unmarried,Black,Female,United-States
16278,Private,10th,Married-civ-spouse,Craft-repair,Husband,White,Male,United-States
16279,Private,HS-grad,Never-married,Craft-repair,Not-in-family,White,Male,Guatemala

0        <=50K
1         >50K
2        <=50K
3        <=50K
4        <=50K
         ...
16275    <=50K
16276     >50K
16277    <=50K
16278    <=50K
16279    <=50K
Name: income, Length: 16280, dtype: str

### Splitting into training and testing data

In [45]:
# Data split for continuous features
X_train_con, X_test_con, y_train_con, y_test_con = train_test_split(continuous_features, y, test_size=0.2)

# Data split for categorical features
X_train_cat, X_test_cat, y_train_cat, y_test_cat = train_test_split(categorical_features, y, test_size=0.2)

print('X_train_continuous: {} X_test_continuous: {} y_train_continuous: {} y_test_continuous: {}'.format(X_train_con.shape, X_test_con.shape, y_train_con.shape, y_test_con.shape))
print('X_train_categorical: {} X_test_categorical: {} y_train_categorical: {} y_test_categorical: {}'.format(X_train_cat.shape, X_test_cat.shape, y_train_cat.shape, y_test_cat.shape))

X_train_continuous: (13024, 5) X_test_continuous: (3256, 5) y_train_continuous: (13024,) y_test_continuous: (3256,)
X_train_categorical: (13024, 8) X_test_categorical: (3256, 8) y_train_categorical: (13024,) y_test_categorical: (3256,)

In [46]:
gaussian_nb = GaussianNB()
categorical_nb = CategoricalNB()

gaussian_nb.fit(X_train_con, y_train_con)
# categorical_nb.fit(X_train_cat, y_train_cat)

GaussianNB()

## 2. Supervised model evaluation

## 3. Extending the model with semi-supervised training

## 4. Supervised model evaluation