##### ### The University of Melbourne, School of Computing and Information Systems
# COMP30027 Machine Learning, 2026 Semester 1

## Assignment 1: Income Classification with Naïve Bayes

**Student ID(s):**     1524206

This iPython notebook is a template which you will use for your Assignment 1 submission.

**NOTE: YOU SHOULD ADD YOUR RESULTS, GRAPHS, AND FIGURES FROM YOUR OBSERVATIONS IN THIS FILE TO YOUR REPORT (the PDF file).** Results, figures, etc. which appear in this file but are NOT included in your report will not be marked.

**Adding proper comments to your code is MANDATORY. **

## 1. Supervised model training

### Reading and pre-processing data

In [22]:
import pandas as pd
import math
import numpy as np

# Reading and pre-processing data
data = pd.read_csv('Assignment1_data/adult_supervised_train.csv', sep=',')
data = data.dropna(how='all')

continuous_features = data[['age','education-num','capital-gain','capital-loss','hours-per-week','income']]
categorical_features = data[['workclass','education','marital-status','occupation','relationship','race','sex','native-country','income']]
display(continuous_features)
display(categorical_features)

       age  education-num  capital-gain  capital-loss  hours-per-week income
0       63              4          3471             0              45  <=50K
1       44             14          7688             0              50   >50K
2       18              8             0             0              30  <=50K
3       39             12             0             0              42  <=50K
4       28              6             0             0              40  <=50K
...    ...            ...           ...           ...             ...    ...
16275   19              7             0             0              56  <=50K
16276   27             13             0          1887              60   >50K
16277   45              9             0             0              40  <=50K
16278   25              6             0             0              45  <=50K
16279   29              9             0             0              40  <=50K

[16280 rows x 6 columns]

,workclass,education,marital-status,occupation,relationship,race,sex,native-country,income
0,Private,7th-8th,Married-civ-spouse,Craft-repair,Husband,White,Male,United-States,<=50K
1,State-gov,Masters,Married-civ-spouse,Prof-specialty,Husband,White,Male,United-States,>50K
2,Private,12th,Never-married,Other-service,Own-child,White,Male,Italy,<=50K
3,Private,Assoc-acdm,Married-civ-spouse,Tech-support,Husband,White,Male,United-States,<=50K
4,Private,10th,Never-married,Handlers-cleaners,Other-relative,White,Male,Mexico,<=50K
...,...,...,...,...,...,...,...,...,...
16275,Private,11th,Never-married,Craft-repair,Not-in-family,White,Male,United-States,<=50K
16276,Private,Bachelors,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,United-States,>50K
16277,State-gov,HS-grad,Separated,Sales,Unmarried,Black,Female,United-States,<=50K
16278,Private,10th,Married-civ-spouse,Craft-repair,Husband,White,Male,United-States,<=50K
16279,Private,HS-grad,Never-married,Craft-repair,Not-in-family,White,Male,Guatemala,<=50K

### Splitting into training and testing data

### Helper functions

In [23]:
def calculate_mean_and_std(input):
  mean = np.mean(input)
  std = np.std(input)
  return mean, std

## 2. Supervised model evaluation

## 3. Extending the model with semi-supervised training

## 4. Supervised model evaluation